@host=http://localhost:8080

### GET PRODUCT

GET {{host}}/products

### GET CATEGORY
GET {{host}}/category


### SIGNUP

POST {{host}}/SignUp
Content-Type: application/json

{
    "email": "abc@fde.fr",
    "password": "Chibi1234",
    "first_name": "ALbert",
    "last_name": "Jean",
    "gender": true,
    "day": "14",
    "month": "02",
    "year": "1782",
    "phone_number": "0678412578",
    "street_number": "2 bis",
    "name_of_the_road": "Rue des lilas",
    "postal_code": "06450",
    "city": "Paris"
}   

### LOGIN

POST {{host}}/login
Content-Type: application/json

{
    "email": "abc@fde.fr",
    "password": "Chibi1234"
}

### FIND USER

GET {{host}}/account/1


### UPDATE USER


PATCH {{host}}/account/1
Content-Type: application/json

{
    "mail": "abc@fae.fr",
    "first_name": "Pierre",
    "last_name": "Marc",
    "gender": true,
    "day": "22",
    "month": "02",
    "year": "1782",
    "phone_number": "0678412578",
    "street_number": "14",
    "name_of_the_road": "Rue des abres",
    "postal_code": "06450",
    "city": "Bordeaux"
} 

### CREATE ORDER

POST {{host}}/order
Content-Type: application/json

{
    "number": "123",
    "total_without_taxes": 5,
    "delivery_street_number": "5",
    "delivery_name_of_the_road": "rue de bagnolet",
    "delivery_postal_code": "75020",
    "delivery_city": "paris",
    "user_id": 1,
    "cart": {
        "line": {
            "order_id": 1,
            "product_id": 23,
            "quantity": 4
        },
        "line": {
            "order_id": 1,
            "product_id": 24,
            "quantity": 2
        },
        "line": {
            "order_id": 1,
            "product_id": 26,
            "quantity": 1
        } 
    }
}

### UPDATE PASSWORD

PATCH {{host}}/newPassword
Content-Type: application/json

{
    "email": "abc@fde.fr",
    "actualPassword": "Chibi1234",
    "newPassword1": "Chibi134",
    "newPassword2": "Chibi124"
}