-- Deploy chibi-api:seeding_product to pg

BEGIN;

INSERT INTO category ("category_name", "category_picture", "state") VALUES 
('Café', '', FALSE),
('Thés et Infusions', '', FALSE),
('Soft', '', FALSE),
('bubbles tea', '', FALSE),
('Sablés décorés', '', TRUE),
('Sablés à peindre', '', TRUE),
('Sablés messages', '', TRUE),
('Sablés personnalisés', '', TRUE),
('Gâteaux', '', TRUE),
('Cornet de Crêpes', '', TRUE),
('Glaces', '', TRUE);

INSERT INTO product ("number", "type_of_product", "product_name", "product_picture", "description", "price_without_taxes", "taxe", "stock", "category_id") VALUES 
('CAF_1', FALSE, 'Espresso', '', '', NULL, NULL, NULL, 1),
('CAF_2', FALSE, 'Double Espresso', '', '', NULL, NULL, NULL, 1),
('CAF_3', FALSE, 'Americano', '', '', NULL, NULL, NULL, 1),
('CAF_4', FALSE, 'Capuccino', '', '', NULL, NULL, NULL, 1),
('CAF_5', FALSE, 'Caramel Macchiato', '', '', NULL, NULL, NULL, 1),
('CAF_6', FALSE, 'Mocha', '', '', NULL, NULL, NULL, 1),
('CAF_7', FALSE, 'Café Latte', '', '', NULL, NULL, NULL, 1),
('CAF_8', FALSE, 'Dalgona Coffe', '', '', NULL, NULL, NULL, 1),
('SD_1', TRUE, 'Coffret Pâques', '', '', 27.40, 5.5, 5, 5),
('SD_2', TRUE, 'Coffret Hmong', '', '', 36.85, 5.5, 8, 5),
('SD_3', TRUE, 'Coffret Mariage', '', '', 27.40, 5.5, 8, 5),
('SD_4', TRUE, 'Coffret Naissance', '', '', 27.40, 5.5, 8, 5),
('SD_5', TRUE, 'Bouquet de fleur', '', '', 27.40, 5.5, 8, 5),
('SD_6', TRUE, 'Coffret éventail Japonais', '', '', 27.40, 5.5, 8, 5),
('SP_1', TRUE, 'Pâques', '', '', 9.35, 5.5, 8, 6),
('SP_2', TRUE, 'Hmong', '', '', 9.35, 5.5, 8, 6),
('SP_3', TRUE, 'Mariage', '', '', 9.35, 5.5, 8, 6),
('SP_4', TRUE, 'Bricolage', '', '', 9.35, 5.5, 8, 6),
('SP_5', TRUE, 'Coffret bouquet de fleur', '', '', 28.25, 5.5, 8, 6),
('SP_6', TRUE, 'Eventail japonais', '', '', 9.90, 5.5, 8, 6),
('SM_1', TRUE, 'Crayon', '', '', 11.34, 5.5, 8, 7),
('SM_2', TRUE, 'Fleurie', '', '', 11.34, 5.5, 8, 7),
('SM_3', TRUE, 'Bricolage', '', '', 23.62, 5.5, 8, 7),
('SM_4', TRUE, 'Biscuit', '', '', 2.36, 5.5, 8, 7),
('SM_5', TRUE, 'Lettre', '', '', 2.83, 5.5, 8, 7),
('SM_6', TRUE, 'Tasse', '', '', 11.34, 5.5, 8, 7),
('TEA_1', FALSE, 'Thé montagne du Fuji', '', '', NULL, NULL, NULL, 2),
('TEA_2', FALSE, 'Thé bleu lactée', '', '', NULL, NULL, NULL, 2),
('TEA_3', FALSE, 'Thé fleur de jade', '', '', NULL, NULL, NULL, 2),
('TEA_4', FALSE, 'Infusion terre de feu', '', '', NULL, NULL, NULL, 2),
('TEA_5', FALSE, 'Infusion mille et une nuit', '', '', NULL, NULL, NULL, 2),
('SOFT_1', FALSE, 'Taro Latte', '', '', NULL, NULL, NULL, 3),
('SOFT_2', FALSE, 'Matcha Latte', '', '', NULL, NULL, NULL, 3),
('SOFT_3', FALSE, 'Dalgona Matcha Latte', '', '', NULL, NULL, NULL, 3),
('SOFT_4', FALSE, 'Chocolat chaud', '', '', NULL, NULL, NULL, 3),
('SOFT_5', FALSE, 'Mocktails', '', '', NULL, NULL, NULL, 3),
('BUBBLE_1', FALSE, 'Matcha', '', 'Au lait', NULL, NULL, NULL, 4),
('BUBBLE_2', FALSE, 'Taro', '', 'Au lait', NULL, NULL, NULL, 4),
('BUBBLE_3', FALSE, 'Haricot rouges', 'Au lait', '', NULL, NULL, NULL, 4),
('BUBBLE_4', FALSE, 'Fraise', '', 'Fruité', NULL, NULL, NULL, 4),
('BUBBLE_5', FALSE, 'Mangue', '', 'Fruité', NULL, NULL, NULL, 4),
('BUBBLE_6', FALSE, 'Litchi', '', 'Fruité', NULL, NULL, NULL, 4),
('GAT_1', FALSE, 'Cookie matcha chocolat blanc', '', '', NULL, NULL, NULL, 9),
('GAT_2', FALSE, 'Cheesecake au yuzu', '', '', NULL, NULL, NULL, 9),
('GAT_3', FALSE, 'Gâteau au pandan', '', '', NULL, NULL, NULL, 9),
('GAT_4', FALSE, 'Riz gluant à la mangue', '', '', NULL, NULL, NULL, 9),
('GAT_5', FALSE, 'Roll cake', '', '(fruit selon la saison)', NULL, NULL, NULL, 9),
('CREPE_1', FALSE, 'Chocapink', '', 'Chocolat, Banane', NULL, NULL, NULL, 10),
('CREPE_2', FALSE, 'Pique Cœur', '', 'Fraise, Banane', NULL, NULL, NULL, 10),
('CREPE_3', FALSE, 'Pomme sucré', '', 'Pomme, Caramel', NULL, NULL, NULL, 10),
('CREPE_4', FALSE, 'Forêt des bois', '', 'Fraise, Myrtille, Framboise', NULL, NULL, NULL, 10),
('CREPE_5', FALSE, 'Cocktail des îles', '', 'Fraise, Mangue, Framboise, Banane', NULL, NULL, NULL, 10),
('CREPE_6', FALSE, 'Graine de folie', '', 'Litchi, Framboise', NULL, NULL, NULL, 10),
('GLACE_1', FALSE, 'Chocolat', '', '', NULL, NULL, NULL, 11),
('GLACE_2', FALSE, 'Vanille', '', '', NULL, NULL, NULL, 11),
('GLACE_3', FALSE, 'Litchi', '', '', NULL, NULL, NULL, 11),
('GLACE_4', FALSE, 'Framboise', '', '', NULL, NULL, NULL, 11),
('GLACE_5', FALSE, 'citron', '', '', NULL, NULL, NULL, 11),
('GLACE_6', FALSE, 'Fraise', '', '', NULL, NULL, NULL, 11);

COMMIT;
